services:
  - type: web
    name: design-doc-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: design-doc-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        value: v6rZc+z2bNfI3m+9xSdo3twlQROZQAcYiQG66KjAfmE=
      - key: JWT_SECRET
        value: v6rZc+z2bNfI3m+9xSdo3twlQROZQAcYiQG66KjAfmE=

  - type: web
    name: design-doc-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://backend-sw3t.onrender.com

databases:
  - name: design-doc-db
    plan: free
    databaseName: design_doc_db
    user: design_doc_user