# Render Deployment Configuration
# This file defines all services and databases for the Design Document Generator

databases:
  - name: design-doc-generator-db
    plan: free # Upgrade to 'starter' or higher for production
    databaseName: design_doc_generator
    user: design_doc_user
    postgresMajorVersion: 15

services:
  # Backend API Service
  - type: web
    name: design-doc-generator-api
    runtime: node
    plan: free # Upgrade to 'starter' or higher for production
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && npm start"
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: design-doc-generator-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: API_VERSION
        value: v1
      - key: API_PREFIX
        value: /api
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000 # 15 minutes
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: DB_POOL_SIZE
        value: 5 # Adjust based on plan
      - key: FRONTEND_URL
        sync: false # Will be set after frontend deployment
      - key: ALLOWED_ORIGINS
        sync: false # Will be set after frontend deployment

  # Frontend Service
  - type: web
    name: design-doc-generator-frontend
    runtime: static
    plan: free # Upgrade for custom domain
    buildCommand: "npm install && npm run build"
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production

# Environment Groups (for shared secrets)
envVarGroups:
  - name: design-doc-generator-secrets
    envVars:
      # AI Provider API Keys - Set these in Render dashboard
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false
      # Admin API Key
      - key: ADMIN_API_KEY
        sync: false
      # Supabase (if using for auth)
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
